vich_uploader:
  db_driver: orm
  mappings:
    user_photos:
      uri_prefix: /uploads/users
      upload_destination: "%kernel.project_dir%/public/uploads/users"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
