vich_uploader:
  db_driver: orm
  mappings:
    user_photos:
      uri_prefix: /uploads/user_photos
      upload_destination: "%kernel.project_dir%/public/uploads/user_photos"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
